import turtle
screen = turtle.Screen()
screen.bgcolor("skyblue")
insta = turtle.Turtle()
insta.color("green")
def leaves(scale, pos):
    insta.begin_fill()
    insta.setposition(0, pos)
    insta.setposition(scale, pos - scale)
    insta.setposition(-scale, pos - scale)
    insta.setposition(0, pos)
insta.end_fill()
leaves(50,20)
leaves(80,0)
leaves(120, -30)
leaves(150, -60)
insta.penup()
insta.goto(20, -120)
insta.pendown()
insta.color("brown")
insta.pensize(1)
insta.begin_fill()
insta.right(90)
insta.forward(40)
insta.right(90)
insta.forward(40)
insta.right(90)
insta.forward(40)
insta.end_fill()
insta.penup()
insta.color("yellow")
insta.goto(-10,10)
insta.begin_fill()
insta.pendown()
for i in range(5):
    insta.forward(40)
    insta.right(144)
insta.end_fill()
insta.penup()
message="Merry Christmas and a Happy New Year"
caption="on this 10th Post of my Instagram Account! :)"
insta.goto(-200, 90)
insta.color("blue")
insta.pendown()
insta.write(message, font=("Arial", 25, bold))
insta.goto(-170, 70)
insta.color("purple")
insta.write(message, font=("Arial", 20, italic))
insta.pendown()
turtle.done()
